package llm

import (
	"context"
	"strings"
	"sync"
	"time"

	"backend/internal/model"
)

var _ Provider = (*MockLLMProvider)(nil)

// MockLLMProvider is a deterministic in-memory provider for testing without external networks.
type MockLLMProvider struct {
	mu               sync.Mutex
	models           []model.LLMModel
	defaultReply     string
	chunkDelay       time.Duration
	simPromptTokens  int
	simComplTokens   int
	shouldFailStream bool
	shouldFailModels bool
}

// NewMockLLMProvider creates a ready-to-use mock provider with default models and replies.
func NewMockLLMProvider() *MockLLMProvider {
	return &MockLLMProvider{
		models:          GetDefaultStaticModels(),
		defaultReply:    "Привет! Это тестовый ответ языковой модели через мок-провайдер.",
		chunkDelay:      5 * time.Millisecond,
		simPromptTokens: 15,
		simComplTokens:  25,
	}
}

// SetDefaultReply configures the default text response generated by StreamChat.
func (m *MockLLMProvider) SetDefaultReply(reply string) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.defaultReply = reply
}

// SetChunkDelay sets the delay between emitted stream chunks.
func (m *MockLLMProvider) SetChunkDelay(d time.Duration) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.chunkDelay = d
}

// SetSimulatedUsage overrides the prompt and completion tokens returned in the done event.
func (m *MockLLMProvider) SetSimulatedUsage(prompt, completion int) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.simPromptTokens = prompt
	m.simComplTokens = completion
}

// SetFailStream forces StreamChat to return an error immediately.
func (m *MockLLMProvider) SetFailStream(fail bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.shouldFailStream = fail
}

// SetFailModels forces GetModels to return an error immediately.
func (m *MockLLMProvider) SetFailModels(fail bool) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.shouldFailModels = fail
}

// GetModels returns the mock models list.
func (m *MockLLMProvider) GetModels(ctx context.Context) ([]model.LLMModel, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if m.shouldFailModels {
		return nil, context.DeadlineExceeded
	}
	res := make([]model.LLMModel, len(m.models))
	copy(res, m.models)
	return res, nil
}

// StreamChat emits words as delta events followed by a final done event.
func (m *MockLLMProvider) StreamChat(ctx context.Context, req model.ChatCompletionRequest) (<-chan model.StreamEvent, <-chan error) {
	events := make(chan model.StreamEvent, 50)
	errs := make(chan error, 1)

	m.mu.Lock()
	reply := m.defaultReply
	delay := m.chunkDelay
	pTokens := m.simPromptTokens
	cTokens := m.simComplTokens
	failStream := m.shouldFailStream
	m.mu.Unlock()

	go func() {
		defer close(events)
		defer close(errs)

		if failStream {
			errs <- context.Canceled
			return
		}

		pPrice, cPrice := AssignFallbackPricing(req.Model)
		words := strings.Fields(reply)

		for i, word := range words {
			select {
			case <-ctx.Done():
				errs <- ctx.Err()
				return
			default:
			}

			chunk := word
			if i < len(words)-1 {
				chunk += " "
			}

			events <- model.StreamEvent{
				Type:    model.StreamEventDelta,
				Content: chunk,
			}

			if delay > 0 {
				select {
				case <-ctx.Done():
					errs <- ctx.Err()
					return
				case <-time.After(delay):
				}
			}
		}

		cost := CalculateTokenCost(pTokens, cTokens, pPrice, cPrice)

		events <- model.StreamEvent{
			Type: model.StreamEventDone,
			Usage: &model.TokenUsage{
				PromptTokens:     pTokens,
				CompletionTokens: cTokens,
				TotalTokens:      pTokens + cTokens,
				CostKopecks:      cost,
			},
		}
	}()

	return events, errs
}
